// Code generated by MockGen. DO NOT EDIT.
// Source: ./store.go
//
// Generated by this command:
//
//	mockgen -source=./store.go -destination=./mock_store.go -package=main
//

// Package main is a generated GoMock package.
package main
